@BASE_URL = https://sandbox-api.brewerydb.com/v2/
@KEY = ?key=16425efea894091210b061870d1e9afb

### LIST BEERS
GET {{BASE_URL}}beers/{{KEY}}

### DETAIL BEER
GET {{BASE_URL}}beer/c4f2KE{{KEY}}

### GET BEER STYLES
GET {{BASE_URL}}styles/{{KEY}}

### ADD BEER
POST {{BASE_URL}}beers/{{KEY}}
Content-Type: application/x-www-form-urlencoded

name=Teste&styleId=1